#!/usr/bin/env python3
"""Derive the decoder's opcode -> mnemonic map from dumpbin, instead of hand-writing it.

Two probe fixtures, both assembled by ml.exe and disassembled by dumpbin:

  probe_1b.asm    every one-byte opcode that takes a ModRM byte, encoded with mod == 3 and
                  operand bytes chosen so the instruction is as short as legal, followed by
                  64 bytes of CC padding so an unknown instruction cannot swallow the next
                  probe.
  probe_0f.asm    every two-byte 0F xx opcode, and every 0F 38 xx / 0F 3A xx three-byte
                  opcode, sampled with one fixed modrm byte.

Each source line carries dumpbin's answer as a trailing comment, e.g.

    db 0Fh, 10h, 0C1h       ; movups

so the expected mnemonic is visible next to the bytes, and the .asm file can be diffed.
`run_tests.py` then checks every probe mnemonic against the decoder.

Why generate rather than write the table by hand: the previous hand-written table was wrong
in a way that still produced plausible output (mandatory-prefix forms mapped to their
unprefixed siblings, so `F3 0F 6F` rendered as `movq mm,mm` instead of `movdqu xmm,xmm`).
An oracle-driven table cannot drift from the oracle.
"""
from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import groundtruth as gt                                        # noqa: E402

PAD = 64            # bytes of int3 after each probe

HEADER = """; GENERATED by make_probe_fixture.py - do not edit by hand.
;
; Each `db` line is one isolated instruction encoding; the trailing comment is dumpbin's
; mnemonic for it. Probing this way means the opcode tables in disasm_lib/x86.py are
; checked against a real disassembler rather than against memory.
.686
.XMM
.model flat, C
option casemap:none

_TEXT SEGMENT
"""

# Opcodes that take a ModRM byte. Those that do not (inc/dec/push/pop, the 0x70-0x7F short
# branches, the x87 escapes, string ops, ...) are excluded: probing them with a fixed modrm
# byte would test nothing.
NO_MODRM = set()
for _i in range(8):
    NO_MODRM |= {0x40 + _i, 0x48 + _i, 0x50 + _i, 0x58 + _i, 0x70 + _i, 0x78 + _i,
                 0xB0 + _i, 0xB8 + _i}
NO_MODRM |= {0x06, 0x07, 0x0E, 0x16, 0x17, 0x1E, 0x1F,
             0x27, 0x2F, 0x37, 0x3F,
             0x60, 0x61, 0x6C, 0x6D, 0x6E, 0x6F,
             0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97,
             0x98, 0x99, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F,
             0xA4, 0xA5, 0xA6, 0xA7, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF,
             0xC3, 0xC9, 0xCB, 0xCC, 0xCE, 0xCF,
             0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF,
             0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xEC, 0xED, 0xEE, 0xEF,
             0xF0, 0xF1, 0xF4, 0xF5, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD}


# Prefix probes. A large part of the 0F space means something different under 66 / F2 / F3,
# and those forms have no unprefixed sibling to inherit from, so they must be probed with the
# prefix present. This sweep is what makes the mandatory-prefix table data rather than memory.
PREFIXES = ((0x66, "66"), (0xF2, "f2"), (0xF3, "f3"))


def build_spec() -> list[tuple[str, bytes]]:
    """[(label, instruction bytes)] for every probe.

    The trailing operand bytes are chosen to satisfy the common shapes at once:
      * a ModRM with mod == 3 (register form) so no displacement is expected, then one more
        byte for the many forms that take an imm8.
      * for the group opcodes, modrm 0xC0 puts /0 in the reg field, which is always a valid
        selector.
    Probes whose real encoding is shorter simply leave unused bytes - they land in the pad
    region and are disassembled separately, which is harmless because the comparison is
    per-probe-line.
    """
    out: list[tuple[str, bytes]] = []

    for op in range(0x100):
        if op in NO_MODRM or op == 0x0F:
            continue
        body = bytes([op, 0xC1, 0x00, 0x00, 0x00, 0x00])
        out.append(("p1_%02X" % op, body))

    # Two-byte 0F xx. 0xC1 -> mod 3, reg 0, rm 1.
    for op2 in range(0x100):
        if op2 in (0x38, 0x3A, 0x0F):
            continue
        out.append(("p0f_%02X" % op2, bytes([0x0F, op2, 0xC1, 0x00, 0x00, 0x00, 0x00])))

    # Three-byte escapes.
    for escape, name in ((0x38, "p38"), (0x3A, "p3a")):
        for op3 in range(0x100):
            n = 4 if escape == 0x3A else 3
            body = bytes([0x0F, escape, op3, 0xC1] + [0x00] * 4)[:n + 3]
            out.append(("%s_%02X" % (name, op3), body))

    # The same two- and three-byte spaces, with each mandatory prefix.
    for pbyte, pname in PREFIXES:
        for op2 in range(0x100):
            if op2 == 0x0F:
                continue
            out.append(("p%s_%02X" % (pname, op2),
                        bytes([pbyte, 0x0F, op2, 0xC1, 0x00, 0x00, 0x00, 0x00])))
        for escape, name in ((0x38, "38"), (0x3A, "3a")):
            for op3 in range(0x100):
                out.append(("p%s%s_%02X" % (pname, name, op3),
                            bytes([pbyte, 0x0F, escape, op3, 0xC1, 0x00, 0x00])))
    return out


def write_asm(path: str, spec: list[tuple[str, bytes]], comments: dict[str, str]) -> None:
    """Write the probe source.

    The instruction bytes go on one `db` line (short), but the padding goes one byte per
    line: MASM rejects a single db list of 64+ operands with "statement too complex", and it
    caps the error count at 100 before giving up, so one over-long list fails the whole file.
    """
    with open(path, "w", encoding="ascii", newline="\r\n") as fh:
        fh.write(HEADER)
        for label, body in spec:
            fh.write("\n%s:\n" % label)
            note = comments.get(label, "")
            # MASM reads a trailing-h literal starting with A-F as an identifier, not a
            # number (`C1h` is "undefined symbol"), so every byte is written with a leading 0.
            fh.write("    db %s%s\n" % (", ".join("0%02Xh" % b for b in body),
                                        ("        ; " + note) if note else ""))
            for _ in range(PAD // 16):
                fh.write("    db %s\n" % ", ".join(["0CCh"] * 16))
        fh.write("\n_TEXT ENDS\n\nEND\n")


def read_comments(path: str) -> dict[str, str]:
    out: dict[str, str] = {}
    cur = None
    for line in open(path, encoding="ascii"):
        m = re.match(r"^(p\w+):\s*$", line.strip())
        if m:
            cur = m.group(1)
            continue
        m = re.match(r"^\s+db\s+[^;]*;\s*(\S+)\s*$", line)
        if m and cur:
            out[cur] = m.group(1)
            cur = None
    return out


def disasm_by_addr(obj: str) -> tuple[dict[int, tuple[str, int]], int]:
    """{address: (mnemonic, byte count)} plus the total number of disassembled bytes.

    Addresses are used rather than dumpbin's label headers: labels only appear for symbols
    dumpbin chooses to print, and a `db`-only segment gets none at all. Walking by address
    works because dumpbin disassembles a COFF section linearly.
    """
    tools = gt.discover_tools()
    obj = os.path.abspath(obj)
    out = gt._run([tools["dumpbin"], "/nologo", "/disasm", obj],
                  os.path.dirname(obj) or ".")
    table: dict[int, tuple[str, int]] = {}
    end = 0
    for line in out.splitlines():
        m = gt._DISASM_LINE.match(line)
        if not m:
            continue
        addr = int(m.group(1), 16)
        raw = bytes.fromhex(m.group(2).replace(" ", ""))
        text = m.group(3).strip()
        mnem = text.split()[0] if text else ""
        table[addr] = (mnem, len(raw))
        end = max(end, addr + len(raw))
    return table, end


def measured(obj: str, spec: list[tuple[str, bytes]]) -> dict[str, tuple[str, int]]:
    """label -> (dumpbin mnemonic, bytes consumed) for each probe, located by address.

    The address walk advances by the *declared* block size (instruction bytes + pad), not by
    the length dumpbin reported: an unknown byte decodes as a 1-byte instruction, and
    advancing by that would slide every later probe out of alignment and silently attribute
    the wrong mnemonic to hundreds of opcodes.
    """
    table, end = disasm_by_addr(obj)
    out: dict[str, tuple[str, int]] = {}
    pos = 0
    for label, body in spec:
        ent = table.get(pos)
        if ent is not None:
            out[label] = ent
        pos += len(body) + PAD
    return out


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "all"
    work = os.path.join(HERE, "_build")
    os.makedirs(work, exist_ok=True)
    spec = build_spec()

    for fname in ("probe_1b.asm", "probe_0f.asm"):
        pass

    spec_1b = [s for s in spec if s[0].startswith("p1_")]
    spec_0f = [s for s in spec if not s[0].startswith("p1_")]

    for fname, part in (("probe_1b.asm", spec_1b), ("probe_0f.asm", spec_0f)):
        path = os.path.join(HERE, fname)
        obj = os.path.join(work, os.path.splitext(fname)[0] + ".obj")
        existing = read_comments(path) if os.path.exists(path) else {}
        if mode in ("all", "gen") or not existing:
            write_asm(path, part, existing)
        gt.build_fixture(path, work)
        found = measured(obj, part)
        comments = {}
        for label, body in part:
            mnem, blen = found.get(label, ("", 0))
            if not mnem:
                continue
            # dumpbin renders an unrecognised byte as `db 0FFh` (or `int 3` for the CC pad).
            # Those are answers too: they say "this opcode is not decodable", which the
            # decoder is allowed to report as an error but never as a made-up instruction.
            if mnem in ("db", "int"):
                comments[label] = "unknown"
            else:
                comments[label] = mnem
        write_asm(path, part, comments)
        known = sum(1 for v in comments.values() if v != "unknown")
        print("%-16s %4d probes, %4d decoded by dumpbin, %4d unknown"
              % (fname, len(part), known, len(comments) - known))
    return 0


if __name__ == "__main__":
    sys.exit(main())
